export interface DetailPullRequest {
  status: number;
  url: string;
  headers: Object;
  data: {
    url: string;
    id: number;
    node_id: string;
    html_url: string;
    diff_url: string;
    patch_url: string;
    issue_url: string;
    number: number;
    state: string;
    locked: boolean;
    title: string;
    user: [Object];
    body: string;
    created_at: string;
    updated_at: string;
    closed_at: null | string;
    merged_at: null | string;
    merge_commit_sha: string;
    assignee: [Object];
    assignees: [Object];
    requested_reviewers: [Object];
    requested_teams: [];
    labels: [];
    milestone: null;
    draft: false;
    commits_url: string;
    review_comments_url: string;
    review_comment_url: string;
    comments_url: string;
    statuses_url: string;
    head: [Object];
    base: [Object];
    _links: [Object];
    author_association: string;
    auto_merge: null | string;
    active_lock_reason: null | string;
    merged: boolean;
    mergeable: boolean;
    rebaseable: boolean;
    mergeable_state: string;
    merged_by: null | string;
    comments: number;
    review_comments: number;
    maintainer_can_modify: boolean;
    commits: number;
    additions: number;
    deletions: number;
    changed_files: number;
  };
}
